Update README phone images
salesforce/offline-app-developer-starter-kit pull request #37
Opened 2023-05-11 18:24 UTC by clivewong

Replace outdated phone images in the README with the currently offline app experience.

2023-05-11 18:39 UTC, dbreese commented on images/OfflineSplash.png
I think we should also change the README.md to state `Launch the Offline App`. Currently it states `Launch the mobile app`.

2023-05-11 18:43 UTC, dbreese commented on images/OfflineRecords.png
I think this image should show the list of Accounts or Contacts, not the briefcase home screen.

2023-05-11 18:45 UTC, clivewong commented on images/OfflineRecords.png
Thanks @dbreese, I'll update OfflineRecords.png to reflect your suggestion.

2023-05-11 18:46 UTC, dbreese requested changes
I think we need to update along with README, too as it is outdated. See comments inline.

2023-05-11 18:49 UTC, clivewong commented on images/OfflineSplash.png
:+1:

2023-05-11 18:53 UTC, clivewong commented on images/OfflineDownload.png
👍

2023-05-11 19:14 UTC, ashwin-SF commented
@clivewong @dbreese when previewing this branch in Git, the image layout on the README file seems a little off. They look stacked, like in the images below. Can we add line breaks between the bullet points and latest images?
![Screenshot 2023-05-11 at 3 03 56 PM](https://github.com/salesforce/offline-app-developer-starter-kit/assets/133263663/ec037904-0d40-4c8e-ba80-6db3bbea1d22)
![Screenshot 2023-05-11 at 3 04 00 PM](https://github.com/salesforce/offline-app-developer-starter-kit/assets/133263663/e0f81865-013e-4373-b7f7-1e58592ae63c)

2023-05-12 18:21 UTC, dbreese commented on README.md
> +- Records:
Images look great! Wondering if we should change `Records:` to `Account Records:` or `Tap on an object (for example Accounts)`?

2023-05-12 18:21 UTC, dbreese approved these changes
LGTM!

2023-05-12 19:58 UTC, ashwin-SF commented
Looks good! Let's ship it!

2023-05-16 18:01 UTC, ashwin-SF commented
@dbreese @khawkins can we merge this PR to main?

2023-05-16 18:22 UTC, dbreese approved these changes
LGTM! Nice!

2023-05-16 18:24 UTC, merged