Adding CI, ESLint, Prettier checks
salesforce/offline-app-developer-starter-kit pull request #9
Opened 2022-10-18 23:40 UTC by khawkins

Fear not, the terrible large changes! I broke the commits up into meaningful chunks, with the last commit being *exclusively* format changes from running `prettier` on the `force-app/**/*.js` files. I'd just ignore that commit, from a review standpoint.

I'd recommend clicking through each of the first 3 commits, one by one, which are not nearly so noisy, and represent the interesting changes to the repo, which are:

- Added Prettier and ESLint as suggested VSCode extensions.
- Updated JS editors to run Prettier on file save.
- Fixed the outstanding ESLint errors in the project.
- Added GitHub Actions CI for all of the above, to keep us honest on PRs going forward.

2022-10-19 00:16 UTC, sfdctaka commented
I'm curious, Kevin, why do test js files don't have semicolons?

2022-10-19 00:17 UTC, sfdctaka commented on force-app/main/default/lwc/editAccountRecord/editAccountRecord.js
> +        window.history.back()
I imagine linting was complaining that it doesn't know `history` object. What is the guidance in prefixing with `window` as opposed to `// eslint-disable-next-line`?

2022-10-19 00:18 UTC, sfdctaka approved these changes
LGTM! Awesome that you broke up in commits. Was very easy to follow.

2022-10-19 03:14 UTC, AdamLiechty requested changes
I would leave the `history.back()` as-is unless confirmed the change is safe on both platforms.

2022-10-19 03:14 UTC, AdamLiechty commented on force-app/main/default/lwc/createAccountRecord/createAccountRecord.js
> +        window.history.back();
IIRC this might have caused some problems on Android at some point. We should check before making this change.

2022-10-19 03:51 UTC, khawkins commented
> I'm curious, Kevin, why do test js files don't have semicolons?

Like, why didn't they have semicolons before? (I think all the JS files basically do now.) JavaScript doesn't strictly require semicolons, employing something known as Automatic Semicolon Insertion (ASI) behind the scenes. ESLint's [`semi` rule docs](https://eslint.org/docs/latest/rules/semi) does a good job of explaining why this "feature" can be problematic, whether you're a JS semicolon adherent or not.

I tend to be (with Prettier) in the "yes semicolons" camp, because I think your intent as a developer should be clear, not left to the interpreter—and then let your linting tools do their best to clean up the mess that ASI has made, the rest of the time.

2022-10-19 03:53 UTC, khawkins commented on force-app/main/default/lwc/createAccountRecord/createAccountRecord.js
> +        window.history.back();
Ah okay. I did not in fact test it out, opting to go with different forums where folks have said that it's an acceptable navigation path for LWCs, where appropriate. For now I'll just add the ignore directives instead, and we can revisit the viability of `window.history` at a later date.

2022-10-19 14:18 UTC, dbreese commented on package.json
> +    "prettier": "prettier --write \"force-app/**/*.js\"",
For this and the `lint` script above, do we want .html and/or .css files, too?

2022-10-19 14:19 UTC, dbreese commented on force-app/main/default/lwc/scanBarcode/__tests__/scanBarcode.test.js
> +import process from 'node:process';
Ah, cool, I wasnt sure how to get this from alerting below even though tests still ran.

2022-10-24 16:23 UTC, khawkins commented on package.json
> +    "prettier": "prettier --write \"force-app/**/*.js\"",
We ran into issues when we went broad-brush, specifically in LWC HTML templates, where `{}` values were being improperly quoted by `prettier`. We could look at ways in which certain style rules could be selectively applied in the future, but for now I just stuck with JS prettying, to be certain.

2022-10-24 16:24 UTC, khawkins commented on force-app/main/default/lwc/scanBarcode/__tests__/scanBarcode.test.js
> +import process from 'node:process';
I'd still like to revisit a better pattern where we're using this, since we *have* been able to demonstrate `await Promise.resolve();` working for other tests, but it still doesn't seem to work here. A battle for another day!

2022-10-27 22:56 UTC, khawkins commented
@AdamLiechty Ping! Could you take a look to make sure I've resolved the `history.back()` request?

2022-10-28 21:32 UTC, merged